<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>k</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Katana</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(0|[1-9][0-9]*)(\.[0-9]+)?((e|E)(\+|\-)[0-9]+)?</string>
			<key>name</key>
			<string>constant.numeric.katana</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|\\)(if|else|while|for|break|continue)\b</string>
			<key>name</key>
			<string>keyword.control.katana</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|\\)(take|do|return)\b</string>
			<key>name</key>
			<string>keyword.other.katana</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|\\)(sizeof|instanceof|in|new)\b</string>
			<key>name</key>
			<string>keyword.operator.katana</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|\\)(import|export|from)\b</string>
			<key>name</key>
			<string>keyword.other.katana</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|\\)(true|false|yes|no|on|off|null|undefined|NaN|infinity|this)\b</string>
			<key>name</key>
			<string>constant.language.katana</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|\\)(var|void|u?int(|8|16|32|64)|float(|32|64)|struct(\s+[\_\$a-zA-Z][\_\$a-zA-Z0-9]*)?|bool)\b</string>
			<key>name</key>
			<string>storage.type.katana</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.katana</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.katana</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.katana</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.katana</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.k</string>
	<key>uuid</key>
	<string>1CE0DFA0-C721-4773-A9C0-9DC994F0202F</string>
</dict>
</plist>
