var a

int b
int8 c
int16 d
int32 e
int64 f

uint g
uint8 h
uint16 i
uint32 j
uint64 k

float l
float32 m
float64 n

bool o

void* p

int() q 
int(int) r 
int(int,float) s

// With initialization
var a2 = this

int b2 = 1
int8 c2 = 1
int16 d2 = 1
int32 e2 = 1
int64 f2 = 1

uint g2 = 1
uint8 h2 = 1
uint16 i2 = 1
uint32 j2 = 1
uint64 k2 = 1

float l2 = 1.0
float32 m2 = 1.0
float64 n2 = 1.0

bool o2 = true

void* p2 = null

void() q2 = do {}
int(int) r2 = take x { return 1 }
float(int,float) s2 = take x, y { return 1.0 }